default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 10) %>

development:
  <<: *default
  database: taskflow_dev

test:
  <<: *default
  database: taskflow_test

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'taskflow_prod') %>
