# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.2'

gem 'rails', '~> 8.1.3'

gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'

# Yes event-sourcing framework (pulled from GitHub main)
git 'https://github.com/yousty/yes.git', branch: 'main', glob: '*/*.gemspec' do
  gem 'yes-command-api'
  gem 'yes-core'
  gem 'yes-read-api'
end

# Cross-origin requests from the Next.js frontend
gem 'rack-cors', '~> 2.0'

# Timezone data on lean Linux images
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development do
  gem 'listen', '~> 3.9'
end

group :development, :test do
  gem 'factory_bot_rails', '~> 6.4'
  gem 'rspec-rails', '~> 7.0'
  gem 'rubocop', '~> 1.64', require: false
  gem 'rubocop-performance', '~> 1.21', require: false
  gem 'rubocop-rails', '~> 2.24', require: false
  gem 'rubocop-rspec', '~> 3.0', require: false
end
